linha1 = input().split(' ')
x, y = linha1
x = float(x)
y = float(y)

# if x > 0 and y > 0:print("Q1")
# if x > 0 and y == 0:print("Eixo X")
# if x < 0 and y == 0:print("Eixo X")          
# if x > 0 and y < 0:print("Q4")    
# if x < 0 and y > 0:print ("Q2")
# if x < 0 and y < 0:print ("Q3")
# if x == 0 and y < 0:print("Eixo Y")
# if x == 0 and y > 0:print("Eixo Y")
# if x == y == 0:print("Origem")

if x > 0 and y > 0:print('Q1')
elif x < 0 and y > 0:print('Q2')
elif x < 0 and y < 0:print('Q3')
elif x > 0 and y < 0:print('Q4')
elif x == 0 and y > 0: print('Eixo Y')
elif x == 0 and y < 0: print('Eixo Y')
elif y == 0 and x > 0: print('Eixo X')
elif y == 0 and x < 0: print('Eixo X')
elif x==y==0:print('Origem')